name: Publish to GHCR

on:
  # Triggers minor version ( vX.Y.Z-ShortHash )
  push:
    branches:
      - main
  # Triggers major version ( vX.Y.Z )
  release:
    types: [created]

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Extract metadata
        id: meta
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

          # Triggered by a release event — versioning as major ( vX.Y.Z )
          if [[ "${GITHUB_EVENT_NAME}" == "release" ]]; then
            TAG_NAME="${{ github.event.release.tag_name }}"
            echo "GIT_TAG=$TAG_NAME" >> $GITHUB_ENV
            echo "IS_RELEASE=true" >> $GITHUB_ENV

          # Triggered by a general push event — versioning as minor ( vX.Y.Z-ShortHash )
          else
            git fetch --tags
            LATEST_TAG=$(git tag --list 'v*.*.*' | sort -V | tail -n1)
            FALLBACK_TAG="${LATEST_TAG:-v0.0.0}"
            echo "GIT_TAG=${FALLBACK_TAG}-${SHORT_SHA}" >> $GITHUB_ENV
            echo "IS_RELEASE=false" >> $GITHUB_ENV
          fi

          echo "REPO_OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image (version tag)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.REPO_OWNER_LC }}/signasl-api:${{ env.GIT_TAG }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Tag and push as latest (if release)
        if: env.IS_RELEASE == 'true'
        run: |
          docker pull ghcr.io/${{ env.REPO_OWNER_LC }}/signasl-api:${{ env.GIT_TAG }}
          docker tag ghcr.io/${{ env.REPO_OWNER_LC }}/signasl-api:${{ env.GIT_TAG }} \
                     ghcr.io/${{ env.REPO_OWNER_LC }}/signasl-api:latest
          docker push ghcr.io/${{ env.REPO_OWNER_LC }}/signasl-api:latest
